import calculator as c
au=input(print ("enter the augend"))
ad=input(print ("enter the addend"))
a=int(au)
b=int(ad)
c.sum(a,b)
mi=input(print ("enter the minuend"))
su=input(print ("enter the subtrahend"))
d=int(mi)
e=int(su)
c.sub(d,e)
mu=input(print ("enter the multiplier"))
mult=input(print ("enter the multiplicand"))
f=int(mu)
g=int(mult)
c.mul(f,g)
divi=input(print ("enter the dividend"))
di=input(print ("enter the divisor"))
h=int(divi)
i=int(di)
c.div(h,i)

